apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-demo-preview
  annotations:
    ingress.kubernetes.io/proxy-body-size: 100M
    ingress.kubernetes.io/app-root: /
spec:
  ingressClassName: nginx-public
  rules:
  - host: signadot-test-canary-preview.rnd.sandbox.codefresh.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: canary-demo-preview
            port:
              name: http
